def add(num1,num2):
    total=num1+num2
    print(f'num1 : {num1} and num2 ={num2}')
    return total
# result=add(num2=12,num1=122)
# print(result)
def multiply(num1,num2):
    result=num1*num2
    return result
# when i gives an argument then its give s an error but when defined a number value in 1 then its run 
#  its run successfully .but when i gives 2nd parameter as a argument its denied defined parameter value
#  this is solve by using kargs
output=multiply(55)
print(output)



